---
- name: install start and enable httpd
  hosts: redos 
  tasks:
  - name: install package
    package:
      name: httpd
      state: latest
  - name: start and enable service
    service:
      name: httpd
      state: started
      enabled: yes
- name: install APACHE
  hosts: ubuntu
  tasks:
  - name: install Apache
    apt:
      name: apache2
      state: present
  - name: start Apache
    service:
      name: apache2
      state: started
      enabled: yes
