---
- name: install start and enable httpd
  gather_facts: false
  hosts: redos
  tasks:
  - name: install package
    package:
      name: httpd
      state: latest
  - name: start and enable service
    service:
      name: httpd
      state: started
      enabled: yes

- name: install start and enable APACHE
  gather_facts: false
  hosts: ubuntu
  tasks:
  - name: install Apache
    apt:
      name: apache2
      state: present
  - name: start Apache
    service:
      name: apache2
      state: started
      enabled: yes

- name: test httpd ansible1
  become: False
  gather_facts: false
  hosts: localhost
  tasks:
  - name: test httpd access ansible1
    uri:
      url: http://ansible1/icons/apache_pb2.gif

  - name: test httpd access ansible2
    uri:
      url: http://ansible2/icons/ubuntu-logo.png

  - name: test httpd access ansible3
    uri:
      url: http://ansible3/icons/apache_pb2.gif